# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-29 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='table',
            field=models.PositiveIntegerField(),
        ),
    ]
