# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-01 17:18
from __future__ import unicode_literals

import booking.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20160430_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reference',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='table.Table'),
        ),
    ]
