# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-01 17:34
from __future__ import unicode_literals

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20160501_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reference',
            field=models.CharField(default=booking.models._generateUniqueReferenceNumber, max_length=10),
        ),
    ]
