# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-03 22:45
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('starter', 'starter'), ('main course', 'main course'), ('dessert', 'dessert'), ('beverage', 'beverage')], max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('popularity', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
