# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-05 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='food',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.Food'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_ordered', to='table.Table'),
        ),
    ]
