# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-05 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_ishistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='isHistory',
            field=models.BooleanField(default=False),
        ),
    ]
