# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-29 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_food_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='food',
            name='popularity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.CharField(choices=[('starter', 'starter'), ('main course', 'main course'), ('dessert', 'dessert'), ('beverage', 'beverage')], max_length=20),
        ),
    ]
