# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20160419_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='type',
            field=models.CharField(default='Hello', max_length=20),
            preserve_default=False,
        ),
    ]
