# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-03 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '__first__'),
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='isAvailable',
        ),
        migrations.AddField(
            model_name='table',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Order'),
        ),
        migrations.AddField(
            model_name='table',
            name='size',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
    ]
