# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-03 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20160503_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='order',
        ),
    ]
