# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-03 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20160503_2348'),
        ('table', '0003_remove_table_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Order'),
        ),
    ]
